studieresan/studs-web

- frontend/app/api.js
- frontend/app/auth.js
- frontend/app/components/A/index.js
- frontend/app/containers/App/actions.js
- frontend/app/containers/App/reducer.js
- frontend/app/containers/Login/index.js
- frontend/app/containers/Members/actions.js
- frontend/app/containers/Navbar/index.js
- frontend/app/containers/User/actions.js
- frontend/app/containers/User/index.js
- frontend/app/containers/User/reducer.js
- frontend/app/routes.js
Authenticating with the new backend and fetching some user info with graphql
> Basic authentication with lint fixes

- frontend/app/api.js
- frontend/app/components/Cv/index.js
- frontend/app/containers/CvEdit/actions.js
- frontend/app/containers/CvEdit/reducer.js
- frontend/app/containers/User/actions.js
- frontend/server/index.js
- frontend/server/logger.js
- frontend/server/middlewares/frontendMiddleware.js
Update cv actions to use new graphql api
> GraphQL CV

- app/api.js
- app/containers/CvEdit/actions.js
- app/containers/CvEdit/index.js
- app/containers/CvEdit/reducer.js
- app/containers/User/index.js
- app/routes.js
> Add a position field to users and a default resume

- app/containers/App/actions.js
- app/containers/Navbar/index.js
- app/containers/User/index.js
- package.json
Fixing some errors and hiding some features to prep for the CV day on monday
> Prepare for cv day

- app/api.js
- app/containers/Navbar/index.js
- app/containers/User/actions.js
- app/containers/User/constants.js
- app/containers/User/index.js
- app/containers/User/messages.js
- app/containers/User/reducer.js
> Ability to reset password

- app/api.js
- app/containers/Members/actions.js
- app/containers/Members/index.js
/members now lists all users using graphql api.
/members/:user-id lists details for a person (no cv)
user id is firstname + lastname lowercased.
> Update members list to use new GraphQL api

- app/api.js
- app/containers/Members/actions.js
- app/containers/Members/reducer.js
Together with https://github.com/studieresan/overlord/pull/10
> Fetch cvs when fetching users

- app/containers/App/styles.css
- app/containers/CvEdit/index.js
- app/containers/User/index.js
Just placing some basic limits on the size of inputs. Backend coming later.
> Basic field validation

- app/components/Cv/index.js
- app/components/Cv/styles.css
- app/components/TextArea/index.js
- app/containers/App/styles.css
- app/containers/CvEdit/actions.js
- app/containers/CvEdit/constants.js
- app/containers/CvEdit/index.js
- app/containers/CvEdit/reducer.js
- app/containers/CvEdit/styles.css
- package.json
- yarn.lock
Many people requested the ability to re-order CV items. This also adds some padding between items which was also requested.
> Reorder items

- app/components/Cv/styles.css
- app/containers/App/styles.css
- app/containers/CvEdit/index.js
- app/containers/CvEdit/styles.css
Also changes the color of the green action button as it before looked like a disabled green:
Also fixes overflow on the text areas (now hiding the scrollbars (need testing in safari)).
> CVEdit moved and changed coloring of the action buttons

- app/containers/CvEdit/index.js
Confirm box with plain old javascript.
> Confirm remove item and section

- app/containers/Navbar/styles.css
- app/index.html
#22.
* Extends page to edges
* Uses safe-area env var when available
> iPhone X support for navbar

- app/components/Cv/styles.css
- app/components/HomePage/HomePageHeader/styles.css
- app/components/MemberListItem/styles.css
- app/containers/CvEdit/styles.css
- app/containers/Members/styles.css
- app/containers/Trip/styles.css
- app/index.html
#22.
Adds iPhone X lanscape support to some views that needed it. 
Unfortunately, there does not seem to be a general way to do this, so each component positioned at the edges gets some styling.
Suggestions?
> iPhone X support for views

- app/api.js
- app/containers/ForgotPassword/index.js
- app/containers/PasswordReset/actions.js
- app/containers/PasswordReset/index.js
- app/containers/PasswordReset/messages.js
- app/containers/PasswordReset/reducer.js
- app/routes.js
Backend PR: https://github.com/studieresan/overlord/pull/13
> Password reset via email

- app/containers/User/index.js
Remove the picture label in user edit, since it doesn't have a corresponding input
> Remove picture label

- app/containers/LocaleToggle/index.js
- app/containers/LocaleToggle/styles.css
- app/i18n.js
Redesign the language selector
> Redesign language selector

- app/components/HomePage/HomePagePitch/index.js
- app/components/Section/index.js
Fix Section proptypes to match react-intl messages instead of strings
> Fix translation messges proptypes

- app/containers/App/reducer.js
The navbar background would not display when entering a page directly.
Set intital redux state to counter this
> Fix navbar background not displaying

- app/components/Button/index.js
- app/components/Button/styles.css
- app/containers/CvEdit/index.js
- app/containers/CvEdit/styles.css
- app/containers/Login/index.js
- app/containers/User/index.js
Add a Button component to simplify dealing with different classes and shit
> Add Button component

- app/components/HomePage/HomePagePitch/styles.css
- app/containers/App/styles.css
Super small common style changes to prepare for the other PRs
> Change some global styles

- app/containers/Login/index.js
- app/containers/Login/styles.css
Redesign the login page
Depends on #35
> Redesign login

- app/containers/App/styles.css
- app/containers/User/index.js
- app/containers/User/styles.css
> Redesign user edit

- app/components/Cv/styles.css
- app/containers/CvEdit/index.js
- app/containers/CvEdit/styles.css
Redesigns the CV edit page
Depends on #35
> Redesign CV edit

- app/api.js
- app/containers/Members/actions.js
This is for using the schema that is live in master.
> Update api to user new graphql queries and mutations

- app/components/CvHeader/styles.css
Avoid squashing profile images on CVs
> Fix image cropping css

- app/api.js
- app/containers/Members/actions.js
Based on #41.
Should be merged after #41 and https://github.com/studieresan/overlord/pull/19.
> Use POST for graphql mutations

- app/api.js
- app/components/CvHeader/index.js
- app/components/CvHeader/styles.css
- app/components/MemberImage/index.js
- app/components/MemberImage/styles.css
- app/containers/User/index.js
- app/containers/User/styles.css
- Add a component `MemberImage` that holds its own styling via props
- Switch to this component in CV edit
- Add this component to user edit page
> Add user picture to User edit page

- app/containers/ForgotPassword/index.js
- app/containers/ForgotPassword/styles.css
- app/containers/PasswordReset/index.js
- app/containers/PasswordReset/styles.css
- app/containers/User/index.js
- app/containers/User/styles.css
> fix password reset styling

- app/index.js
- config/webpack.config.dev.js
- package.json
- yarn.lock
Adds hot-reloading with `react-hot-loader`
> Add hot reloading

- app/components/MasterDetail/styles.css
- app/components/MemberListItem/styles.css
- app/containers/Members/index.js
- app/containers/Members/messages.js
- app/containers/Members/styles.css
- app/translations/en.json
- app/translations/se.json
Add a header to the list of members on `/members`
> Add member list header

- app/components/EventDetail/styles.css
- app/components/EventEdit/styles.css
- app/components/EventListItem/styles.css
- app/components/EventStaticDetail/styles.css
- app/components/IndicatorIcon/styles.css
- app/components/MemberHomePage/styles.css
- app/components/MembersStaticDetail/styles.css
- app/components/PublicEvent/styles.css
- app/components/PublicEventMenu/styles.css
- app/containers/Events/styles.css
- app/containers/PublicEvents/styles.css
> Remove stylelint disable comments

- app/api.js
- app/auth.js
- app/containers/App/actions.js
- app/containers/AuthenticatedRoute/index.js
- app/containers/Navbar/index.js
- app/containers/User/actions.js
- app/routes.js
👆 
will (sort of) require https://github.com/studieresan/overlord/pull/17    /
> Logout the user if requests turn out to not be authenticated

- app/containers/App/styles.css
I don't know where this went, but it should definitely be there
> fix line height

- app/components/HomePage/HomePageAbout/index.js
- app/components/HomePage/HomePageAbout/messages.js
- app/components/HomePage/HomePageAbout/styles.css
- app/components/HomePage/index.js
- app/components/MemberImage/index.js
- app/containers/HomePage/index.js
- app/translations/en.json
- app/translations/se.json
Adds a section on the homepage with a random studs member and a link to the About page
> Adds About promotion to homepage

- app/components/EventEdit/index.js
- app/components/EventEdit/messages.js
- app/containers/Login/index.js
- app/containers/Login/messages.js
- app/containers/User/index.js
- app/containers/User/messages.js
- app/translations/se.json
There were some missing translations.
> Added some missing se translations

- yarn.lock
To avoid nasty versioning problems in production :heart: 
> Don't upset the `yarn` core developers; "Please commit your `yarn.lock` files."
https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/
> Adding lockfile

- app/index.js
- package.json
- yarn.lock
Adds Sentry for frontend logging when in prod :lollipop:
> Add sentry for frontend logging

- .eslintrc.json
- .flowconfig
- app/components/TextArea/index.js
- package.json
- yarn.lock
This PR adds Flow for static type checking. I added some basic types to `TextArea` to try it out, and it seems to work.
> Add Flow for type checking

- .eslintrc.json
- app/api.js
- app/components/EventEdit/index.js
- app/containers/CreateUser/formUtils.js
- app/containers/CreateUser/index.js
- app/containers/CreateUser/styles.css
- app/containers/Events/index.js
- app/containers/User/index.js
- app/routes.js
This PR adds a page in `/create-user` with a form to create a new user. It looks like this:
> Add create user view

- app/components/CvHeader/index.js
* Adds member's position to their info header.
* Bonus: makes email and phone clickable.
> Add position to member header

- app/api.js
- app/components/CvHeader/index.js
- app/components/CvHeader/styles.css
- app/containers/App/actions.js
- app/containers/User/index.js
- app/containers/User/messages.js
- app/containers/User/reducer.js
This commit also adds icons to the CV header for LinkedIn and Github.
> Add Github to CV

- app/api.js
- app/auth.js
- app/containers/App/actions.js
Adds JWT tokens to the request to `overlord` in order to solve problem with Safari.
> Adding JWT login test code for Safari

- app/components/Cv/styles.css
- app/components/CvHeader/styles.css
- app/components/MasterDetail/styles.css
- app/containers/CvEdit/styles.css
- app/containers/Events/styles.css
- app/containers/Members/styles.css
- app/containers/Navbar/index.js
- app/translations/se.json
Some alignment fixes, some beautifications. For example, the "saved" indicator now has a transparent background and floats around nicely. The social icons are aligned to the bottom instead, (let me know what you think). Grammar error in navbar fixed.
> General fixes to styling

- app/components/HomePage/HomePagePitch/index.js
- app/components/HomePage/HomePagePitch/styles.css
> Create new home page pitch view

- app/App.js
- app/components/MemberListItem/index.js
- app/components/PublicEventMenu/index.js
- app/utils.js
> Add some tracking just because

- app/containers/Login/styles.css
Updated the background for the login page.
> Update login background

- app/components/Cv/index.js
- app/components/Cv/styles.css
- app/components/CvHeader/index.js
- app/components/MasterDetail/index.js
- app/containers/App/actions.js
- app/containers/App/constants.js
- app/containers/App/reducer.js
- app/containers/Navbar/index.js
- public/index.html
There's a small 'Print CV' button below each CV now. Pressing that prints the CV (duh).
> Add support for printing a single CV

- app/components/Cv/index.js
- app/components/Cv/styles.css
- app/components/CvHeader/index.js
- app/components/CvHeader/styles.css
- app/components/EventFeedback/styles.css
- app/index.css
This pull request improves the appearance of CVs when printing.
(As usual, printing works best in Chrome)
> Improve CV layout for printing

- app/components/EventEdit/index.js
- app/components/EventEdit/messages.js
- app/components/EventEdit/styles.css
- app/containers/Events/actions.js
- app/containers/Events/constants.js
- app/containers/Events/index.js
- app/containers/Events/reducer.js
- app/translations/se.json
This PR fixes the EventEdit component and related stuff.
> Fix creating events

- .eslintrc.json
- app/api.js
- app/containers/CreateEventFeedback/MissingPeople.js
- app/containers/CreateEventFeedback/index.js
- app/containers/CreateEventFeedback/styles.css
* I changed an eslint rule from error to warning because it's really obnoxious when trying to prototype code.
* `:eventId/create-event-feedback` now shows who hasn't submitted feedback to this particular event.
> Missing people list

- app/containers/CreateEventFeedback/Fieldset.js
- app/containers/CreateEventFeedback/index.js
- app/containers/CreateEventFeedback/styles.css
- app/containers/CreateEventFeedback/template.js
* Fix formatting for text responses for event feedback
* Fill in zeroes in number responses
> Feedback fixes

- app/containers/SalesTool/SalesTool.js
Shows the amount sold for in the companies-view.
> Accumulate and show amount for filtered companies

- app/api.js
- app/components/CompanyHeader/index.js
- app/components/CompanyHeader/styles.css
- app/components/YearPicker/index.js
- app/components/YearPicker/styles.css
- app/containers/About/index.js
- app/containers/App/actions.js
- app/containers/HomePage/index.js
- app/containers/Members/actions.js
- app/containers/Members/index.js
- app/containers/SalesTool/CompanyDetails.js
- app/containers/SalesTool/CompanyDetailsContainer.js
- app/containers/SalesTool/SalesTool.js
- app/containers/SalesTool/SalesToolContainer.js
- app/containers/SalesTool/styles.css
- app/containers/User/reducer.js
- app/store/salesTool/actions.js
- app/store/salesTool/comments/actions.js
- app/store/salesTool/companies/actions.js
- app/store/salesTool/constants.js
- app/store/salesTool/reducer.js
- netlify.toml
- yarn.lock
Front end changes for the Sales Tool that adds a "year picker". This year picker adds the ability to navigate the information of the sales tool for a given year.
Needs the changes in [this backend branch](https://github.com/studieresan/overlord/tree/studs-year) to function.
> Year picker

- app/api.js
- app/containers/PDF/index.js
- app/containers/PDF/styles.css
- app/routes.js
Adds two endpoints to display the Swedish and English info-pdfs.
> Add pdf endpoint
